apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudnative
  namespace: argocd
spec:
  description: Project for applications from cloudnative-gitops repository
  sourceRepos:
    - 'https://github.com/AbdullahMahiBD/iit-workshop-gitops.git'
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ClusterRole
    - group: ''
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
